os: linux
dist: focal
language: node_js
node_js:
  - lts/*
branches:
  only:
    - main
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
cache:
  npm: false
  directories:
    - "~/.pnpm-store"
before_install:
  - corepack enable
  - corepack prepare pnpm@latest-8 --activate
  - pnpm config set store-dir ~/.pnpm-store
install:
  - pnpm install
script:
  - pnpm run lint
  - pnpm run coverage
deploy:
  provider: npm
  api_token:
    secure: MTKCbO/7A5fDvXTtaDiLj64MolEMQFli5QcqowyMOMzQoL3TOfs3msq8qnwK+REAuPodEpw88LqHePDjGjJZ5sdqwq1eER+STD8A0Cy96fkZS7CQ0lTf63pEdhSrw++WrWHDsa4e74aVJJ71oDoVBN0XszG97g1eJXszvT5gF0wVjOlliCFM/hW6cQ2+1kVaLvHnU8tcGt5/u5ff3yTwjiKUCWte3RC9LwtQwruySDWxkthbgBIe1HF8RN1t/XY2/CicQz901/mC2t7lfPsfWbqvSduENBEcAo70IkGedJULPLas/nczeThD0H9Ch5QpoM7aSiQ6sEojvh+rt6SM32KP4Vd64mllp1PASLTnkOfAiGVonD7NNtmAj/CnmSbl5un2/yrwqr2jRAo41/oEWWpycJ0s2WUavkCjG8f1B7pD3gzJR/OPAgcnfvEJIEnHabcp9ZootD/8F5eX19OUkvFYSE979a1YGRrJWrdfJyPHMJnTYxnl/kXGXlNVv65YsvM1pI/9AtYECutvqf5vlI8CfKY1lHgOnSOa4ENoBgxAcETTWGdclGZd513mV10pnizFGKiPEfenNL0IuubKK2muMbn/DY5W/jf5pZZ9K/cyANbRdGJYg8vEi+Jkyi+l+JZ/FqAn0d3nrmaUsNgAQso3QlgWYIZSbASScj6qG2s=
  on:
    tags: true
  edge: true